title: This Life
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4265233
  brandStrength: 0.375
  lightness: 0.5625
  brandColors:
    - '#2e3a00'
    - '#b1b1a7'
    - '#82804f'
    - '#060400'
    - '#f0ab51'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Kay.B.Imagery
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.41026
layout_spectrum: 0.4713262
