name: Kay.B.Imagery
favicon: null
layout_spectrum: 0.5217261912766844
typography_spectrum: 0.574232303770259
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.30759518360719085
  lightness: 0.9456399707123637
  saturation: 0.8464276490267366
  rhythmicContrast: 0.2179466295056045
purpose: []
