name: Kay.B.Imagery
favicon: null
layout_spectrum: 0.91039
typography_spectrum: 0.11269
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e3a00'
    - '#b1b1a7'
    - '#82804f'
    - '#060400'
    - '#f0ab51'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
